### PR TITLE
Switching Theme Via Url Params

### PR DESCRIPTION
**Pull request by alijah-etch**
Switches theme from url words separated by --

### CODE REVIEW

**Comment by alijah-etch** [comment]
> 

It's to account for spacing in Theme names

**Comment by gavmck** [comment]
> > 
> 
> It's to account for spacing in Theme names

You can use spaces in the query string though `?theme=dark theme` is valid

**Comment by alijah-etch** [comment]
> You can use spaces in the query string though `?theme=dark theme` is valid
I changed it to be done with just spaces or preferred %20 which is more consistent

**Review by gavmck — APPROVED** [review]

**Comment by gavmck** [comment]
Thanks!

**Pull request merged**
